version: '3.8'

services:
  backend:
    build: ./backend
    container_name: student_performance_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models:/models
    environment:
      - WANDB_API_KEY=YOUR_API_KEY_HERE
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    container_name: student_performance_frontend
    ports:
      - "5173:80"  
    depends_on:
      - backend