_wandb:
    value:
        cli_version: 0.26.1
        e:
            jzjbfswu56lfvfkn01npacthpqafustn:
                codePath: notebooks/wandb.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                disk:
                    /:
                        total: "289164750848"
                        used: "191738023936"
                email: 2351010189tam@ou.edu.vn
                executable: T:\Anaconda\python.exe
                git:
                    commit: c04237b76987598d338b8d0a1f5931e1020e6c1d
                    remote: https://github.com/nahtzm/Student_Performance_Prediction.git
                host: Sung-Jin-Woo
                memory:
                    total: "16516440064"
                os: Windows-11-10.0.26200-SP0
                program: notebooks/wandb.ipynb
                python: CPython 3.13.11
                root: T:\Student_Performance_Prediction\notebooks
                startedAt: "2026-04-29T05:34:22.193689Z"
                writerId: jzjbfswu56lfvfkn01npacthpqafustn
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.11
            "5": 0.26.1
            "8":
                - 1
                - 3
            "12": 0.26.1
            "13": windows-amd64
max_depth:
    value: 5
model:
    value: RandomForestRegressor
n_estimators:
    value: 100
random_state:
    value: 42
